// The book template for *Crafting Interpreters*, in Typst.
//
// This file holds all of the design: page geometry, the layout with a wide
// outer margin for the margin notes, the heading styles, the code listing
// styles and the boxes for "Challenges" and "Design Note" sections.
//
// The chapter files in `chapters/` are generated by `tools/typstbuild` and only
// call the helpers defined here:
//
//   #chapter(number: "4", title: "Scanning") <chap-scanning>
//   #section(number: "4.1", title: "The Interpreter Framework")
//   #snippet(file: "lox/Lox.java", change: [add after #emph[main]()])[
//     #codeline("insert", (("k", "if"), ("", " (x) {")))
//   ]
//   #note[This ends up in the outer margin.]
//
// Everything works in both left-to-right (English) and right-to-left (Arabic)
// mode: `#show: book.with(lang: "ar")` flips the binding, the text direction
// and the side the margin notes are placed on.

// --- Design tokens ---------------------------------------------------------

#let primary = rgb("#1481b8")       // hsl(200, 80%, 40%)
#let primary-dark = rgb("#004466")  // hsl(200, 100%, 20%)
#let dark = rgb("#29313d")          // hsl(215, 20%, 20%)
#let light = rgb("#dee9ed")         // hsl(195, 30%, 90%)
#let lighter = rgb("#eef4f7")       // hsl(195, 35%, 95%)
#let warm-dark = rgb("#595959")     // hsl(40, 0%, 35%)
#let warm-light = rgb("#faf8f5")    // hsl(40, 30%, 97%)
#let warm-3 = rgb("#b3a99a")
#let warm-4 = rgb("#ded7c9")
#let warm-5 = rgb("#f4f0e8")
#let design-green = rgb("#f6f8f2")

// Syntax highlighting, straight from the book's CSS.
#let code-colors = (
  k: rgb("#0099e6"),  // keyword
  n: rgb("#dd713c"),  // number
  s: rgb("#c38e22"),  // string
  e: rgb("#e8ba30"),  // string escape
  c: rgb("#aaa8a7"),  // comment
  a: rgb("#9966cc"),  // preprocessor, annotation
  i: rgb("#1b6e98"),  // identifier
  t: rgb("#00a4b2"),  // type name
  err: rgb("#c0392b"),
  comma: rgb("#595959"),
)

#let serif-font = ("Source Serif 4", "Amiri", "Noto Naskh Arabic")
#let sans-font = ("Source Sans 3", "Amiri", "Noto Naskh Arabic")
#let mono-font = "Source Code Pro"

//: Whether the document is right-to-left. `book()` sets it; `note()` reads it.
#let doc-rtl = state("doc-rtl", false)

// --- Document --------------------------------------------------------------

#let book(lang: "en", body) = {
  let is-rtl = lang == "ar"
  doc-rtl.update(is-rtl)

  set page(
    width: 7in,
    height: 9.25in,
    margin: (inside: 0.9in, outside: 1.45in, top: 0.8in, bottom: 0.85in),
    binding: if is-rtl { right } else { left },
    // `none` would make `ref(...)` -- the page numbers in the table of
    // contents -- fail with "cannot reference without page numbering".
    numbering: "1",
    footer: context {
      let page-number = counter(page).get().first()
      if page-number > 1 [
        #set text(size: 8pt, font: sans-font, fill: warm-dark)
        #align(center)[#page-number]
      ]
    },
  )

  set text(
    font: serif-font,
    size: if is-rtl { 11pt } else { 10pt },
    lang: lang,
    dir: if is-rtl { rtl } else { ltr },
    hyphenate: true,
  )
  set par(
    justify: true,
    leading: if is-rtl { 0.8em } else { 0.68em },
    spacing: if is-rtl { 1.05em } else { 0.95em },
    first-line-indent: 0pt,
  )
  show raw: it => text(it, font: mono-font, size: 0.9em, lang: "en", dir: ltr)

  body
}

// --- Headings --------------------------------------------------------------

#let chapter(number: none, title: none) = {
  pagebreak(weak: true)
  heading(level: 1, outlined: true, bookmarked: true)[
    #if number != none [
      #block(above: 0em, below: 0.35em)[
        #set text(size: 30pt, weight: 300, font: sans-font, fill: primary)
        #number
      ]
    ]
    #set text(size: 23pt, weight: 600, font: sans-font, fill: dark)
    #title
  ]
  v(0.5em)
}

#let part-page(title: none, number: none) = {
  pagebreak(weak: true)
  block(height: 2.1in)[]
  heading(level: 1, outlined: true, bookmarked: true)[
    #if number != none [
      #block(above: 0em, below: 0.3em)[
        #set text(size: 13pt, weight: 600, font: sans-font, fill: primary)
        #context {
          // The letterspacing the English label wears would break Arabic's
          // cursive joining, so only the left-to-right edition gets it.
          if doc-rtl.get() {
            [الجزء #number]
          } else {
            set text(tracking: 0.08em)
            [Part #number]
          }
        }
      ]
    ]
    #set text(size: 26pt, weight: 600, font: sans-font, fill: dark)
    #title
  ]
  v(0.5em)
}

#let section(number: none, title: none) = {
  v(0.8em)
  heading(level: 2, outlined: true, bookmarked: true)[
    #if number != none [
      #box(baseline: 0.07em)[
        #text(number, size: 0.8em, font: sans-font, fill: primary, weight: 600)
      ]
      #h(0.45em)
    ]
    #set text(size: 15pt, weight: 600, font: sans-font, fill: dark)
    #title
  ]
  v(-0.2em)
}

#let subsection(number: none, title: none) = {
  v(0.7em)
  heading(level: 3, outlined: true, bookmarked: true)[
    #if number != none [
      #box(baseline: 0.07em)[
        #text(number, size: 0.8em, font: sans-font, fill: primary, weight: 600)
      ]
      #h(0.45em)
    ]
    #set text(size: 12.5pt, weight: 600, font: sans-font, fill: dark)
    #title
  ]
  v(-0.15em)
}

// --- Margin notes ----------------------------------------------------------

#let note(bottom: false, body) = context {
  // Placed in the outer margin, next to the paragraph that mentions it.
  //
  // `bottom` records the Markdown's `<aside class="bottom">`. On the website
  // that class lets the script hang the note *up* from the line it annotates
  // (there is no room below it); here the float layout does the same job by
  // deferring the note to the next page when the column has no room left, so
  // every note hangs from its anchor line the same way.
  let is-rtl = doc-rtl.get()
  place(
    top + end,
    float: true,
    clearance: 1em,
    dx: if is-rtl { -0.8in } else { 0.8in },
    scope: "parent",
  )[
    #box(
      width: 1.2in,
      inset: (x: 6pt, y: 2pt),
      stroke: if is-rtl { (right: 0.8pt + warm-4) } else { (left: 0.8pt + warm-4) },
    )[
      #set text(
        size: 8pt,
        font: sans-font,
        fill: warm-dark,
        lang: if is-rtl { "ar" } else { "en" },
        dir: if is-rtl { rtl } else { ltr },
      )
      #set par(justify: false, spacing: 0.5em, leading: 0.62em)
      #body
    ]
  ]
}

// --- Epigraph --------------------------------------------------------------

#let epigraph(quote: none, cite: none) = {
  block(above: 0.1em, below: 1.1em, inset: (x: 0.1in))[
    #set text(size: 9.5pt, style: "italic", fill: warm-dark)
    #set par(justify: false)
    #quote
    #if cite != none [
      #v(0.3em)
      #set text(size: 9pt, style: "normal")
      #align(end)[#text(cite, fill: primary)]
    ]
  ]
}

// --- Lists -----------------------------------------------------------------

#let bullet-list(body) = {
  block(above: 0.35em, below: 0.35em, width: 100%)[
    #set par(first-line-indent: 0pt, spacing: 0.55em)
    #body
  ]
}

#let numbered-list(body) = {
  block(above: 0.35em, below: 0.35em, width: 100%)[
    #set par(first-line-indent: 0pt, spacing: 0.55em)
    #counter("book-item").update(1)
    #body
  ]
}

#let _item(marker: none, body: none) = {
  block(above: 0.32em, below: 0.32em, width: 100%)[
    #grid(
      columns: (0.3in, 1fr),
      align: (end + top, start + top),
      column-gutter: 0.08in,
      [
        #set text(font: sans-font, size: 9pt, fill: primary)
        #marker
      ],
      body,
    )
  ]
}

#let bullet-item(body) = _item(marker: [•], body: body)

#let numbered-item(body) = {
  _item(marker: context [#counter("book-item").display()], body: body)
  counter("book-item").step()
}

// --- Margin content: challenges and design notes ---------------------------

#let challenges(body) = {
  block(
    width: 100%,
    inset: (x: 12pt, y: 9pt),
    radius: 3pt,
    fill: lighter,
    above: 1.1em,
    below: 1.1em,
  )[
    #set text(size: 9.5pt, font: sans-font)
    #set par(leading: 0.62em, spacing: 0.6em)
    #set text(size: 15pt, weight: 600, fill: dark, font: sans-font)
    #block(above: 0em, below: 0.45em)[Challenges]
    #set text(size: 9.5pt, weight: 400, fill: black, font: sans-font)
    #body
  ]
}

#let design-note(title: none, body) = {
  block(
    width: 100%,
    inset: (x: 12pt, y: 9pt),
    radius: 3pt,
    fill: design-green,
    above: 1.1em,
    below: 1.1em,
  )[
    #set text(size: 15pt, weight: 600, fill: dark, font: sans-font)
    #block(above: 0em, below: 0.45em)[
      #context if doc-rtl.get() [ملاحظة تصميم: ] else [Design Note: ]
      #title
    ]
    #set text(size: 9.5pt, weight: 400, fill: black, font: sans-font)
    #set par(leading: 0.62em, spacing: 0.6em)
    #body
  ]
}

// --- Code listings ---------------------------------------------------------

#let inline-code(value) = box[
  #set text(font: mono-font, size: 0.9em, lang: "en", dir: ltr)
  #text(value, fill: dark)
]

#let _token-color(token) = {
  if token in code-colors { code-colors.at(token) } else { rgb("#3d3d3d") }
}

#let codeline(kind, runs, note: none) = {
  let is-insert = kind == "insert"
  let is-context = kind == "context-before" or kind == "context-after"

  block(
    width: 100%,
    above: 0pt,
    below: 0pt,
    inset: (x: 6pt, y: 0.5pt),
    fill: if is-insert { warm-5 } else { none },
    stroke: if is-insert { (left: 2pt + warm-4) } else { none },
  )[
    #set par(justify: false, leading: 0.6em, spacing: 0pt)
    #set text(font: mono-font, size: 8pt, lang: "en", dir: ltr, hyphenate: false)
    #if runs.len() == 0 [
      #box(height: 0.95em)[]
    ] else [
      #runs.map(((token, value)) => {
        let color = if is-context { rgb("#a8a29a") } else { _token-color(token) }
        if token == "comma" { text(value, fill: warm-dark, weight: "bold") }
        else { text(value, fill: color) }
      }).join()
    ]
    #if note != none [
      #note
    ]
  ]
}

#let snippet(file: none, change: none, lines: none, body) = {
  block(width: 100%, above: 0.9em, below: 0.9em)[
    #if file != none [
      #block(above: 0em, below: 0.25em, outset: (x: 6pt))[
        #set text(size: 8pt, font: sans-font, fill: warm-dark)
        #emph(file)#if change != none [#text(", ")#change]#if lines != none [#text(", ")#lines]
      ]
    ]
    #body
  ]
}

#let listing(lang: none, body) = {
  block(width: 100%, above: 0.9em, below: 0.9em)[
    #body
  ]
}

// --- Figures and tables ----------------------------------------------------

//: A small image that sits inside a sentence, like the GC color dots.
#let inline-figure(src, width: 0.36in) = box(
  baseline: -0.18em,
  image(src, width: width),
)

#let book-figure(src, width: 80%, alt: none) = block(
  width: 100%,
  above: 1em,
  below: 1em,
  align(
    center,
    if alt == none { image(src, width: width) }
    else { image(src, width: width, alt: alt) },
  ),
)

#let book-table(columns: 1, header: (), rows: ()) = {
  block(width: 100%, above: 1em, below: 1em)[
    #set text(size: 9pt, font: sans-font)
    #table(
      columns: columns,
      inset: (x: 2pt, y: 4pt),
      stroke: none,
      align: start + horizon,
      ..if header.len() > 0 {
        (
          table.header(..header.map(cell => block(
            stroke: (bottom: 1pt + light),
            inset: (y: 3pt),
          )[#cell])),
        )
      } else { () },
      ..rows.map(row => row.map(cell => block(
        stroke: (bottom: 0.5pt + light),
        inset: (y: 3pt),
      )[#cell])).flatten(),
    )
  ]
}

// --- Front matter ----------------------------------------------------------

#let title-page() = {
  pagebreak(weak: false)
  block(height: 0.5in)[]
  align(center)[
    #context if doc-rtl.get() [
      #text(size: 32pt, weight: 600, font: sans-font, fill: dark)[صناعة المفسّرات]
      #v(0.3em)
      #text(size: 15pt, font: sans-font, fill: primary)[Crafting Interpreters]
    ] else [
      #text(size: 32pt, weight: 600, font: sans-font, fill: dark)[Crafting Interpreters]
    ]
    #v(0.3em)
    #text(size: 13pt, font: sans-font, fill: warm-dark)[Robert Nystrom]
    #v(1.3em)
    #image("/site/image/header.png", width: 76%)
    #v(1.3em)
    #block(inset: (x: 0.35in))[
      #set text(size: 9.5pt, font: sans-font, fill: warm-dark)
      #set par(justify: true, leading: 0.62em)
      *Crafting Interpreters* contains everything you need to implement a
      full-featured, efficient scripting language. You'll learn both high-level
      concepts around parsing and semantics and gritty details like bytecode
      representation and garbage collection.
      #v(0.5em)
      Starting from `main()`, you build a language that features rich syntax,
      dynamic typing, garbage collection, lexical scope, first-class functions,
      closures, classes, and inheritance.
    ]
  ]
  pagebreak(weak: false)
}

#let dedication-page(image-src: none, line: none) = {
  pagebreak(weak: true)
  block(height: 2.5in)[]
  align(center)[
    #if image-src != none [ #image(image-src, width: 45%) ]
    #v(1em)
    #set text(size: 11pt, style: "italic", fill: warm-dark)
    #if line != none [ #line ]
  ]
}

#let toc-entry(level: 0, number: none, title: none, label: none, note: false) = context {
  let is-rtl = doc-rtl.get()
  block(
    width: 100%,
    above: if level == 0 { 0.6em } else { 0.02em },
    below: 0pt,
    inset: if level == 0 { (x: 0pt) } else if is-rtl { (right: 0.3in) } else { (left: 0.3in) },
  )[
    #set text(
      font: sans-font,
      size: if level == 0 { 10.5pt } else { 9pt },
      weight: if level == 0 { 600 } else { 400 },
      fill: if level == 0 { dark } else { warm-dark },
    )
    #grid(
      columns: (1fr, auto),
      align: (start + bottom, end + bottom),
      gutter: 0.35em,
      [
        #if number != none [#text(fill: primary, weight: 600)[#number]#h(0.45em)]
        #if note [
          #context if doc-rtl.get() [
            #text(fill: warm-3, size: 0.85em)[ملاحظة ]
          ] else [
            #text(fill: warm-3, size: 0.85em)[note ]
          ]
        ]
        #title
      ],
      [
        #set text(size: 8pt, fill: warm-dark)
        #if label != none [ #link(label)[#ref(label, form: "page")] ]
      ],
    )
  ]
}

#let table-of-contents(body) = {
  pagebreak(weak: true)
  heading(level: 1, outlined: false, bookmarked: true)[
    #set text(size: 23pt, weight: 600, font: sans-font, fill: dark)
    #context if doc-rtl.get() [جدول المحتويات] else [Table of Contents]
  ]
  v(0.6em)
  body
}
