"""The build script: weaves ``book/`` + ``java/`` + ``c/`` into Typst sources.

Usage::

    python3 -m typstbuild                       # generate every .typ file
    python3 -m typstbuild --lang ar             # only the Arabic sources
    python3 -m typstbuild --pdf                 # ... and typeset the PDFs
    python3 -m typstbuild --only scanning       # just one chapter

The generated files live in ``typst/``: one Typst file per chapter
(``typst/chapters/*.typ``) plus the document roots ``main.typ`` and
``main-ar.typ``.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
import textwrap
from pathlib import Path
from typing import Optional

from . import mdparse as md
from .emit import TypstEmitter
from .i18n import label_for, title_for
from .model import Book, Page
from .text import to_file_name, typst_string, word_count

FRONT_MATTER_TITLES = {"Crafting Interpreters", "Table of Contents"}


class BookIndex:
    """The set of labels that exist in the generated Typst sources.

    Links in the prose point at ``scanning.html`` or
    ``representing-code.html#metaprogramming-the-trees``; mapping those to
    Typst labels gives the PDF working internal cross references.
    """

    def __init__(self, book: Book):
        self.labels: set[str] = set()
        for page in book.pages:
            self.labels.add(f"chap-{page.file_name}")
            for header in page.headers.values():
                if header.level == 2 and not header.is_special:
                    self.labels.add(f"chap-{page.file_name}-{header.anchor}")
                elif header.is_special:
                    self.labels.add(f"chap-{page.file_name}-{header.anchor}")

    def label_for_href(self, href: str) -> Optional[str]:
        if not href.endswith(".html") and ".html#" not in href:
            return None
        if "#" in href:
            file_part, fragment = href.split("#", 1)
        else:
            file_part, fragment = href, ""
        name = file_part[:-len(".html")]
        label = f"chap-{name}"
        if fragment:
            label += f"-{fragment}"
        return label if label in self.labels else None


# ---------------------------------------------------------------------------
# Chapter emission
# ---------------------------------------------------------------------------


def translate_page(book: Book, page: Page, lang: str, root: Path) -> Page:
    """Points *page* at the translated Markdown file, when there is one."""
    if lang == "en":
        return page
    translated = root / "book" / "ar" / f"{page.file_name}.md"
    if translated.exists():
        page.set_markdown_path(str(translated))
    return page


def emit_page(book: Book, page: Page, index: BookIndex, lang: str, out_dir: Path) -> str:
    """Generates the Typst file for one page and returns its file name."""
    parser = md.MarkdownParser(book, page)
    blocks = parser.parse(_clean_lines(page.lines))

    emitter = TypstEmitter(book, page, lang=lang)
    emitter.index = index  # type: ignore[attr-defined]
    source = emitter.render(blocks)

    chapter_dir = "chapters-ar" if lang == "ar" else "chapters"
    path = out_dir / chapter_dir / f"{page.file_name}.typ"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source, encoding="utf-8")

    for warning in emitter.warnings:
        print(f"  warning: {warning}", file=sys.stderr)

    return f"{chapter_dir}/{page.file_name}.typ"


def _clean_lines(lines: list[str]) -> list[str]:
    """Resolves the book's reference-style links before parsing.

    The Markdown uses ``[text][label]`` plus a list of ``[label]: url``
    definitions at the bottom of each chapter.
    """
    definitions: dict[str, str] = {}
    kept: list[str] = []

    for line in lines:
        match = re.match(r"^\[([^\]]+)\]:\s*(\S+)\s*$", line)
        if match is not None:
            definitions[match.group(1).lower()] = match.group(2)
            continue
        kept.append(line)

    if not definitions:
        return lines

    text = "\n".join(kept)

    def replace(match: re.Match) -> str:
        label = (match.group(2) or match.group(1)).lower()
        url = definitions.get(label)
        if url is None:
            return match.group(0)
        return f"[{match.group(1)}]({url})"

    text = re.sub(r"\[([^\]]+)\]\[([^\]]*)\]", replace, text)
    return text.split("\n")


# ---------------------------------------------------------------------------
# Front matter
# ---------------------------------------------------------------------------


def emit_title_page(lang: str, out_dir: Path) -> str:
    path = out_dir / "frontmatter" / "title.typ"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "// Generated by tools/typstbuild.\n"
        '#import "../template/book.typ": *\n\n'
        "#title-page() <chap-index>\n",
        encoding="utf-8",
    )
    return "frontmatter/title.typ"


def emit_dedication(book: Book, page: Page, lang: str, out_dir: Path) -> str:
    """The dedication page is a centered image plus a line of text."""
    image_src = "none"
    text_value = "none"

    for block in md.MarkdownParser(book, page).parse(_clean_lines(page.lines)):
        if isinstance(block, md.ImageBlock):
            image_src = f'"{"/site/" + block.src.lstrip("/")}"'
        elif isinstance(block, md.Paragraph):
            emitter = TypstEmitter(book, page, lang=lang)
            value = emitter.emit_inline_nodes(block.inlines)
            if value.strip():
                text_value = f"[{value}]"

    path = out_dir / "frontmatter" / "dedication.typ"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "// Generated by tools/typstbuild.\n"
        '#import "../template/book.typ": *\n\n'
        f"#dedication-page(image-src: {image_src}, line: {text_value}) <chap-dedication>\n",
        encoding="utf-8",
    )
    return "frontmatter/dedication.typ"


def emit_contents(book: Book, lang: str, out_dir: Path) -> str:
    """The table of contents, with live page references."""
    lines = [
        "// Generated by tools/typstbuild.",
        '#import "../template/book.typ": *',
        "",
        "#table-of-contents[",
    ]

    for page in book.pages:
        if page.is_part:
            lines.append(
                f'  #toc-entry(number: "{page.number_string}.", '
                f'title: {typst_string(title_for(page.title, lang))}, '
                f"label: <chap-{page.file_name}>)"
            )
            continue

        if page.title in FRONT_MATTER_TITLES:
            if page.title == "Table of Contents":
                continue
            lines.append(
                f"  #toc-entry(title: {typst_string(title_for(page.title, lang))}, "
                f"label: <chap-{page.file_name}>)"
            )
            continue

        number = f"{page.number_string}." if page.number_string else none_string()
        lines.append(
            f'  #toc-entry(number: "{number}", title: "{page.title}", '
            f"label: <chap-{page.file_name}>)"
        )

        for header in page.headers.values():
            if not header.is_special:
                continue
            anchor = header.anchor
            title = (
                label_for("challenges", lang)
                if header.is_challenges
                else header.name.replace("Design Note: ", "")
            )
            lines.append(
                f"  #toc-entry(level: 1, title: {typst_string(title)}, "
                f"label: <chap-{page.file_name}-{anchor}>, note: true)"
            )

    lines.append("] <chap-contents>")
    lines.append("")

    path = out_dir / "frontmatter" / "contents.typ"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return "frontmatter/contents.typ"


def none_string() -> str:
    return ""


# ---------------------------------------------------------------------------
# Document root
# ---------------------------------------------------------------------------


def emit_main(book: Book, includes: list[str], lang: str, out_dir: Path) -> Path:
    name = "main.typ" if lang == "en" else "main-ar.typ"
    path = out_dir / name
    lines = [
        "// Generated by tools/typstbuild -- the document root.",
        f'#import "template/book.typ": *',
        f'#show: book.with(lang: "{lang}")',
        "",
    ]
    for include in includes:
        lines.append(f'#include "{include}"')
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def build_language(book: Book, index: BookIndex, lang: str, out_dir: Path, only: Optional[str]):
    includes: list[str] = []
    stats = {"words": 0, "code": 0}

    for page in book.pages:
        if only and only not in page.file_name:
            continue

        if page.title == "Crafting Interpreters":
            includes.append(emit_title_page(lang, out_dir))
            continue

        if page.title == "Table of Contents":
            includes.append(emit_contents(book, lang, out_dir))
            continue

        translate_page(book, page, lang, Path(book.root))

        if page.title == "Dedication":
            includes.append(emit_dedication(book, page, lang, out_dir))
            stats["words"] += sum(word_count(line) for line in page.lines)
            continue

        includes.append(emit_page(book, page, index, lang, out_dir))
        stats["words"] += sum(word_count(line) for line in page.lines)

    return includes, stats


def compile_pdf(root: Path, out_dir: Path, main: Path, pdf_path: Path) -> None:
    import typst

    typst.compile(
        str(main),
        output=str(pdf_path),
        root=str(root),
        font_paths=[str(out_dir / "fonts")],
        ignore_system_fonts=True,
    )


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="typstbuild", description=__doc__)
    parser.add_argument("--root", default=".", help="repository root")
    parser.add_argument("--out", default="typst", help="output directory for .typ files")
    parser.add_argument(
        "--lang", default="both", choices=["en", "ar", "both"], help="which edition to build"
    )
    parser.add_argument("--only", default=None, help="only build pages matching this substring")
    parser.add_argument("--pdf", action="store_true", help="also typeset the PDFs")
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    out_dir = (root / args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Reading sources from {root} ...")
    book = Book(str(root))
    index = BookIndex(book)

    languages = ["en", "ar"] if args.lang == "both" else [args.lang]
    for lang in languages:
        if lang != "en":
            # Point the pages at their translated Markdown *before* indexing,
            # so the cross references of this edition use the anchors the
            # translated headings produce.
            for page in book.pages:
                translate_page(book, page, lang, root)
            index = BookIndex(book)
        includes, stats = build_language(book, index, lang, out_dir, args.only)  # type: ignore[arg-type]
        main_path = emit_main(book, includes, lang, out_dir)
        print(
            f"[{lang}] wrote {len(includes)} files, "
            f"{stats['words']:,} words of prose -> {main_path.relative_to(root)}"
        )

        if args.pdf and not args.only:
            pdf_path = out_dir / ("crafting-interpreters.pdf" if lang == "en" else "crafting-interpreters-ar.pdf")
            try:
                compile_pdf(root, out_dir, main_path, pdf_path)
            except Exception as error:  # pragma: no cover - reported to the user
                print(f"[{lang}] PDF failed: {error}", file=sys.stderr)
                return 1
            print(f"[{lang}] typeset {pdf_path.relative_to(root)}")

    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
