"""Renders the Markdown AST into Typst source.

The generated chapters are thin: they only call the helpers defined in
``typst/template/book.typ`` (``#chapter``, ``#section``, ``#snippet``,
``#codeline``, ``#note`` ...).  All the visual design lives in the template, so
the generated files stay diffable and readable.
"""

from __future__ import annotations

import re
from typing import Optional

from . import mdparse as md
from .highlight import highlight, strip_aside_marker
from .i18n import DESIGN_NOTE_PREFIXES, title_for
from .model import Book, CodeTag, Page, Snippet
from .text import escape_typst, typst_string

TAB = "  "


def _runs_literal(runs: list[tuple[str, str]]) -> str:
    """Renders highlighted runs as a Typst array of ``(type, text)`` pairs."""
    parts = []
    for token_type, text in runs:
        parts.append(f"({typst_string(token_type)}, {typst_string(text)})")
    return "(" + ", ".join(parts) + ("," if len(parts) == 1 else "") + ")"


class TypstEmitter:
    def __init__(
        self,
        book: Book,
        page: Page,
        lang: str = "en",
        chapter_dir: str = "chapters",
        index=None,
    ):
        self.book = book
        self.page = page
        self.lang = lang
        self.chapter_dir = chapter_dir
        self.index = index
        self.asides: dict[str, md.Aside] = {}
        self.used_asides: set[str] = set()
        #: Names of the asides that have their own block in this page. Those
        #: are emitted where the block is; the matching `<span name="...">`
        #: is only an anchor and must not emit the note a second time.
        self.aside_blocks: set[str] = set()
        self.snippets_used: list[CodeTag] = []
        self.warnings: list[str] = []

    # -- Public API --------------------------------------------------------

    def render(self, blocks: list[md.Block]) -> str:
        self._collect_asides(blocks)

        lines: list[str] = []
        lines.append("// Generated by tools/typstbuild from " + self.page.markdown_path)
        lines.append("// Do not edit by hand: run `make typst` instead.")
        lines.append('#import "../template/book.typ": *')
        lines.append("")
        lines.extend(self._page_title(blocks))
        lines.extend(self.emit_blocks(blocks))
        lines.append("")

        # Any margin note whose anchor we never found still has to appear,
        # so that no text is lost.
        for name, aside in self.asides.items():
            if name not in self.used_asides:
                self.warnings.append(
                    f"{self.page.markdown_path}: aside '{name}' has no anchor"
                )

        return "\n".join(lines)

    # -- Asides ------------------------------------------------------------

    def _collect_asides(self, blocks: list[md.Block]) -> None:
        for block in blocks:
            if isinstance(block, md.Aside):
                self.asides[block.name] = block
                self.aside_blocks.add(block.name)
            elif isinstance(block, md.ListBlock):
                for item in block.items:
                    self._collect_asides(item)
            elif isinstance(block, md.Quote):
                self._collect_asides(block.blocks)

    def _emit_blocks_joined(self, blocks: list[md.Block], indent: int = 0) -> list[str]:
        """Like :meth:`_emit_blocks_spaced`, but returns flat lines."""
        out: list[str] = []
        for group in self._emit_blocks_spaced(blocks, indent):
            out.extend(group)
        return out

    def _aside_content(self, name: str, bare: bool = False) -> Optional[str]:
        aside = self.asides.get(name)
        if aside is None:
            return None
        self.used_asides.add(name)
        body = "\n".join(self.emit_blocks(aside.blocks, indent=1))
        # Inside a function call's argument list we are in code mode, where a
        # leading `#` is not allowed.
        prefix = "" if bare else "#"
        return f"{prefix}note[\n{body}\n]"

    def _page_title(self, blocks: list[md.Block]) -> list[str]:
        """Emits the page's own title.

        The book's Markdown only has level-2 and level-3 headings: the title
        of a page lives in the table of contents in ``tool/lib/src/book.dart``
        and is rendered by the surrounding template. Here the template is
        Typst, so the title becomes a real heading with the label that the
        cross references in other chapters point at.
        """
        if any(isinstance(block, md.Heading) and block.level == 1 for block in blocks):
            return []
        if not self.page.title:
            return []

        title = typst_string(escape_typst(title_for(self.page.title, self.lang)))
        label = f" <chap-{self.page.file_name}>"

        if self.page.is_part:
            number = (
                f', number: "{self.page.number_string}"' if self.page.number_string else ""
            )
            return [f"#part-page(title: {title}{number}){label}", ""]

        if self.page.number_string:
            return [
                f'#chapter(number: "{self.page.number_string}", title: {title}){label}',
                "",
            ]
        return [f"#chapter(title: {title}){label}", ""]

    # -- Blocks ------------------------------------------------------------

    def emit_blocks(self, blocks: list[md.Block], indent: int = 0) -> list[str]:
        """Emits *blocks*, separated by blank lines.

        Typst merges consecutive lines of markup into a single paragraph, so
        blocks have to be separated explicitly.
        """
        groups = self._block_groups(blocks, indent)
        out: list[str] = []
        for group in groups:
            if out:
                out.append("")
            out.extend(group)
        return out

    def _block_groups(self, blocks: list[md.Block], indent: int = 0) -> list[list[str]]:
        """Emits each block into its own group of lines."""
        groups: list[list[str]] = []
        index = 0
        while index < len(blocks):
            block = blocks[index]

            # A "Challenges" or "Design Note" heading wraps everything up to
            # the next section in a box.
            if (
                isinstance(block, md.Heading)
                and block.header is not None
                and block.header.is_special
            ):
                tail, index = self._collect_special(blocks, index + 1)
                groups.append(self._emit_special_heading(block, tail, indent))
                continue

            lines = self.emit_block(block, indent)
            if lines:
                groups.append(lines)
            index += 1
        return groups

    def _collect_special(
        self, blocks: list[md.Block], start: int
    ) -> tuple[list[md.Block], int]:
        """Collects the blocks that belong inside a Challenges/Design Note box."""
        collected: list[md.Block] = []
        index = start
        while index < len(blocks):
            block = blocks[index]
            if isinstance(block, md.Heading) and block.level <= 2:
                break
            collected.append(block)
            index += 1
        return collected, index

    def _emit_special_heading(
        self, heading: md.Heading, tail: list[md.Block], indent: int
    ) -> list[str]:
        pad = TAB * indent
        assert heading.header is not None
        body = self.emit_blocks(tail, indent + 1)
        title = "".join(self.emit_inline(node) for node in heading.inlines)

        label = f" <chap-{self.page.file_name}-{heading.header.anchor}>"

        lines: list[str] = []
        if heading.header.is_challenges:
            lines.append(f"{pad}#challenges[")
            lines.extend(body)
            lines.append(f"{pad}]{label}")
        else:
            # The template prints the "Design Note: " prefix itself.
            for prefix in DESIGN_NOTE_PREFIXES:
                if title.startswith(prefix):
                    title = title[len(prefix):]
                    break
            lines.append(f"{pad}#design-note(title: {typst_string(title)})[")
            lines.extend(body)
            lines.append(f"{pad}]{label}")
        return lines

    def emit_block(self, block: md.Block, indent: int = 0) -> list[str]:
        pad = TAB * indent

        if isinstance(block, md.Heading):
            return self._emit_heading(block, indent)

        if isinstance(block, md.Paragraph):
            return [pad + self.emit_inline_nodes(block.inlines)]

        if isinstance(block, md.SnippetBlock):
            return self._emit_snippet(block, indent)

        if isinstance(block, md.CodeFence):
            return self._emit_code_fence(block, indent)

        if isinstance(block, md.Aside):
            if block.name in self.used_asides:
                return []
            content = self._aside_content(block.name)
            if content is None:
                return []
            return [pad + content.replace("\n", "\n" + pad)]

        if isinstance(block, md.Quote):
            return self._emit_quote(block, indent)

        if isinstance(block, md.ListBlock):
            return self._emit_list(block, indent)

        if isinstance(block, md.ImageBlock):
            return self._emit_image(block, indent)

        if isinstance(block, md.Table):
            return self._emit_table(block, indent)

        if isinstance(block, md.RawListing):
            return self._emit_raw_listing(block, indent)

        if isinstance(block, md.Div):
            # The challenges/design-note/dedication divs are implied by the
            # headings; nothing to emit.
            return []

        if isinstance(block, md.HorizontalRule):
            return [pad + "#v(0.5em)"]

        raise AssertionError(f"Unknown block {block!r}")

    def _emit_heading(self, heading: md.Heading, indent: int) -> list[str]:
        pad = TAB * indent
        title = self.emit_inline_nodes(heading.inlines)
        header = heading.header

        if heading.level == 1:
            label = f" <chap-{self.page.file_name}>"
            if self.page.is_chapter and self.page.number_string:
                return [
                    f'{pad}#chapter(number: "{self.page.number_string}", title: "{title}"){label}'
                ]
            return [f'{pad}#part-page(title: "{title}"){label}']

        number = header.number_string(self.page) if header is not None else None
        label = ""
        if header is not None:
            label = f" <chap-{self.page.file_name}-{header.anchor}>"

        if heading.level == 2:
            if number:
                return [f'{pad}#section(number: "{number}", title: "{title}"){label}']
            return [f'{pad}#section(title: "{title}"){label}']

        if number:
            return [f'{pad}#subsection(number: "{number}", title: "{title}"){label}']
        return [f'{pad}#subsection(title: "{title}"){label}']

    # -- Code --------------------------------------------------------------

    def _emit_snippet(self, block: md.SnippetBlock, indent: int) -> list[str]:
        pad = TAB * indent
        try:
            tag = self.page.find_code_tag(block.name)
        except KeyError:
            self.warnings.append(
                f"{self.page.markdown_path}: unknown code tag '{block.name}'"
            )
            return [f"{pad}// MISSING SNIPPET: {block.name}"]

        snippet = self.book.find_snippet(tag)
        if snippet is None:
            self.warnings.append(
                f"{self.page.markdown_path}: no source snippet for '{block.name}'"
            )
            return [f"{pad}// MISSING SNIPPET: {block.name}"]

        self.snippets_used.append(tag)

        args: list[str] = []
        if tag.show_location:
            description = snippet.description
            args.append(f"file: {typst_string(description.file)}")
            if description.change:
                args.append(f"change: [{_change_content(description.change)}]")
            if description.lines:
                args.append(f"lines: {typst_string(description.lines)}")

        lines = [f"{pad}#snippet({', '.join(args)})["]

        language = snippet.file.language
        body_lines = self._snippet_code_lines(snippet, language)
        lines.extend(body_lines)
        lines.append(f"{pad}]")
        return lines

    def _snippet_code_lines(self, snippet: Snippet, language: str) -> list[str]:
        out: list[str] = []
        inner = TAB * 1

        if snippet.added_comma is not None:
            text, _ = strip_aside_marker(snippet.added_comma)
            runs = highlight(language, [text])[0]
            if text.endswith(","):
                # Split the comma off so the template can highlight it.
                runs = _split_trailing_comma(runs)
            out.append(
                inner + f"#codeline(\"comma\", {_runs_literal(runs)})"
            )

        for kind, code_lines in (
            ("context-before", snippet.context_before),
            ("insert", snippet.added),
            ("context-after", snippet.context_after),
        ):
            # A `// [name]` marker is only an anchor for the aside: it is
            # stripped from the code and the note itself is emitted (once)
            # where its <aside> block sits, like the Dart tool does for the
            # HTML output.
            marked = [strip_aside_marker(line)[0] for line in code_lines]
            highlighted = highlight(language, marked)
            for runs in highlighted:
                args = f'"{kind}", {_runs_literal(runs)}'
                out.append(inner + f"#codeline({args})")
        return out

    def _emit_code_fence(self, block: md.CodeFence, indent: int) -> list[str]:
        pad = TAB * indent
        language = block.lang or "text"
        lines = [f'{pad}#listing(lang: {typst_string(language)})[']

        if language == "text":
            highlighted = [[("", line[block.indent :] if len(line) > block.indent else line)] for line in block.lines]
        else:
            highlighted = highlight(language, block.lines)

        for runs in highlighted:
            lines.append(f"{TAB}#codeline(\"insert\", {_runs_literal(runs)})")
        lines.append(f"{pad}]")
        return lines

    def _emit_raw_listing(self, block: md.RawListing, indent: int) -> list[str]:
        pad = TAB * indent
        args: list[str] = []
        if block.file:
            args.append(f"file: {typst_string(block.file)}")
        if block.change:
            args.append(f"change: [{_change_content(block.change)}]")

        lines = [f"{pad}#snippet({', '.join(args)})["]
        for kind, group in (
            ("context-before", block.context_before),
            ("insert", block.insert),
            ("context-after", block.context_after),
        ):
            for runs in group:
                lines.append(f'{TAB}#codeline("{kind}", {_runs_literal(runs)})')
        lines.append(f"{pad}]")
        return lines

    # -- Other blocks ------------------------------------------------------

    def _emit_quote(self, block: md.Quote, indent: int) -> list[str]:
        pad = TAB * indent
        cite: Optional[list[md.Inline]] = None
        body_blocks: list[md.Block] = []

        for inner in block.blocks:
            if isinstance(inner, md.Paragraph):
                remaining: list[md.Inline] = []
                found_cite = None
                for node in inner.inlines:
                    if isinstance(node, md.Cite):
                        found_cite = node
                    elif found_cite is None:
                        remaining.append(node)
                    else:
                        remaining.append(node)
                if found_cite is not None:
                    cite = found_cite.children
                    if remaining:
                        body_blocks.append(md.Paragraph(remaining))
                    continue
            body_blocks.append(inner)

        body = "\n".join(self.emit_blocks(body_blocks, indent + 1))
        lines = [f"{pad}#epigraph("]
        lines.append(f"{TAB}quote: [")
        lines.extend(body.split("\n"))
        lines.append(f"{TAB}],")
        if cite is not None:
            lines.append(f"{TAB}cite: [{self.emit_inline_nodes(cite)}],")
        lines.append(f"{pad})")
        return lines

    def _emit_list(self, block: md.ListBlock, indent: int) -> list[str]:
        pad = TAB * indent
        item_function = "numbered-item" if block.ordered else "bullet-item"
        lines: list[str] = []
        for item in block.items:
            body = self.emit_blocks(item, indent + 1)
            lines.append(f"{pad}#{item_function}[")
            lines.extend(body)
            lines.append(f"{pad}]")
        function = "#numbered-list" if block.ordered else "#bullet-list"
        return [f"{pad}{function}[", *lines, f"{pad}]"]

    def _emit_image(self, block: md.ImageBlock, indent: int) -> list[str]:
        pad = TAB * indent
        src = "/site/" + block.src.lstrip("/")
        width = {"wide": "100%", "above": "55%", "": "80%"}.get(block.klass, "80%")
        alt = typst_string(block.alt)
        return [
            f"{pad}#book-figure({typst_string(src)}, width: {width}, alt: {alt})"
        ]

    def _emit_table(self, block: md.Table, indent: int) -> list[str]:
        pad = TAB * indent
        columns = len(block.header) or (len(block.rows[0]) if block.rows else 1)
        lines = [f"{pad}#book-table(columns: {columns}, header: ("]
        for cell in block.header:
            lines.append(f"{TAB}[{self.emit_inline_nodes(cell)}],")
        lines.append(f"{pad}), rows: (")
        for row in block.rows:
            lines.append(f"{TAB}(")
            for cell in row:
                lines.append(f"{TAB * 2}[{self.emit_inline_nodes(cell)}],")
            lines.append(f"{TAB}),")
        lines.append(f"{pad}))")
        return lines

    # -- Inline ------------------------------------------------------------

    def emit_inline_nodes(self, nodes: list[md.Inline]) -> str:
        return "".join(self.emit_inline(node) for node in nodes)

    def emit_inline(self, node: md.Inline) -> str:
        if isinstance(node, md.Text):
            return escape_typst(node.value)
        if isinstance(node, md.Emph):
            return f"#emph[{self.emit_inline_nodes(node.children)}]"
        if isinstance(node, md.Strong):
            return f"#strong[{self.emit_inline_nodes(node.children)}]"
        if isinstance(node, md.CodeSpan):
            return f"#inline-code({typst_string(node.value)})"
        if isinstance(node, md.Link):
            text = self.emit_inline_nodes(node.children)
            index = getattr(self, "index", None)
            label = index.label_for_href(node.href) if index is not None else None
            if label is not None:
                return f"#link(<{label}>)[{text}]"
            if node.href.startswith(("http://", "https://", "mailto:")):
                return f"#link({typst_string(node.href)})[{text}]"
            # A dead internal link (a page that isn't part of this edition) is
            # better as plain emphasized text than as a broken link.
            return text
        if isinstance(node, md.Anchor):
            if node.name in self.aside_blocks:
                # The note is emitted next to its own <aside> block.
                return ""
            note = self._aside_content(node.name)
            if note is None:
                return ""
            return note
        if isinstance(node, md.LineBreak):
            return "#linebreak()"
        if isinstance(node, md.SmallCaps):
            return f"#smallcaps[{escape_typst(node.value)}]"
        if isinstance(node, md.Cite):
            return f"#emph[{self.emit_inline_nodes(node.children)}]"
        if isinstance(node, md.ImageInline):
            return f'#inline-figure({typst_string("/site/" + node.src.lstrip("/"))})'
        raise AssertionError(f"Unknown inline {node!r}")

def _change_content(runs: list[tuple[str, str]]) -> str:
    """Renders a snippet caption ("in scanToken()") as Typst markup.

    The parens have to stay inside the `#emph[...]` call: a bare `()` right
    after a content block would be parsed as calling that content.
    """
    merged: list[tuple[str, str]] = []
    for kind, text in runs:
        if merged and kind == "text" and text and merged[-1][0] == "em" and text.startswith("()"):
            merged[-1] = ("em", merged[-1][1] + "()")
            text = text[2:]
            if not text:
                continue
        merged.append((kind, text))

    out = []
    for kind, text in merged:
        if kind == "em":
            out.append(f"#emph[{escape_typst(text)}]")
        else:
            out.append(escape_typst(text))
    return "".join(out)


def _split_trailing_comma(runs: list[tuple[str, str]]) -> list[tuple[str, str]]:
    """Moves a trailing comma of the last run into its own ``comma`` run."""
    if not runs:
        return runs
    token_type, text = runs[-1]
    if text.endswith(","):
        result = runs[:-1]
        if text[:-1]:
            result.append((token_type, text[:-1]))
        result.append(("comma", ","))
        return result
    return runs


def _starts_block(line: str) -> bool:
    """Whether a line begins a block-level Typst element (so it needs its own
    paragraph break before it)."""
    stripped = line.lstrip()
    if not stripped.startswith("#"):
        return False
    return bool(
        re.match(
            r"#(chapter|part-page|section|subsection|snippet|listing|challenges|"
            r"design-note|note|epigraph|bullet-list|numbered-list|bullet-item|"
            r"numbered-item|book-figure|book-table|table-of-contents)\b",
            stripped,
        )
    )
